### Get all products
GET http://127.0.0.1:8000/products/
Accept: application/json

###

### Create a new product
POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNDQyNDA0LCJpYXQiOjE3NjA0NDIxMDQsImp0aSI6IjFhZDRjNzdkMjNiODRhYzc5NjQxMjFmY2MyZjgzMjlhIiwidXNlcl9pZCI6IjEifQ.FSiaQROsugxojuQhpPq_XLYoOEqCiyH03ePtKqtPgME

{
  "name": "Product 1",
  "price": 10.99,
  "description": "Description of product 1",
  "stock": 100
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{ "username": "admin", "password": "test" }

###

GET http://127.0.0.1:8000/user-orders/
Accept: application/json

###
# Write for get refresh token from /api/token/refresh/
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDUyOTQ1NywiaWF0IjoxNzYwNDQzMDU3LCJqdGkiOiJmY2FiMzE4MTkwNmI0MzUyOTg0YWY0NzY2NjJjYjU4ZSIsInVzZXJfaWQiOiIxIn0.A6KFwcFUDvCvksX3QHFk7NNqf5uflngtf5msNPetTis" }
