### Get all products
GET http://127.0.0.1:8000/products/
Accept: application/json

###
GET http://127.0.0.1:8000/products/2/ HTTP/1.1

###
PUT http://127.0.0.1:8000/products/2/
Content-Type: application/json

{
  "name": "Product 2",
  "price": 10,
  "description": "Description of product 2",
  "stock": 10
}

###
DELETE http://127.0.0.1:8000/products/1/

###

### Create a new product
POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzkyNTk5LCJpYXQiOjE3NjA3OTIyOTksImp0aSI6IjYyMDM2ODk4YmEwNzRkNDI5YzM0OTU4YTAyN2NiZjcwIiwidXNlcl9pZCI6IjEifQ.DxCF2WND2UWnIdarOditx9JdQamSOSw2BimDmOyb66s

{
  "name": "Product 1",
  "price": 10.99,
  "description": "Description of product 1",
  "stock": 100
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{ "username": "Komol", "password": "Gx7!dYp@92#fLm$Q" }

###

GET http://127.0.0.1:8000/user-orders/
Accept: application/json

###
# Write for get refresh token from /api/token/refresh/
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDg3OTczNywiaWF0IjoxNzYwNzkzMzM3LCJqdGkiOiJjNjQ1MWU5OWM1NDY0OTJlOWY4ODU5NWEyMDY0Y2I1MSIsInVzZXJfaWQiOiIyIn0.Esfd0tM6sQe7DaK3OADS6mWfgxYZJWm6Z8PF327bNrQ" }

###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzkyNzExLCJpYXQiOjE3NjA3OTI0MTEsImp0aSI6IjkyNzEwMjViOWI3ZDQ3ZmE5Nzc2ZWNiM2VjZjljMjZlIiwidXNlcl9pZCI6IjIifQ.WGqmTXgGnyqbmHT30Y-3Xq0kl9xSp7sly1a41uMS4Xg

{
  "status": "pending",
  "items": [
    {
      "product": 2,
      "quantity": 1
    },
    {
      "product": 3,
      "quantity": 1
    }
  ]
}

###
GET http://127.0.0.1:8000/orders/d75f6760-e075-4f4c-ab4f-b8c1d41ae5ad
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzk0MTA2LCJpYXQiOjE3NjA3OTM4MDYsImp0aSI6IjI5YWU0YzY1ZDA1ODRkNzdhODk1ZGY2Y2M5MzI2MGRiIiwidXNlcl9pZCI6IjIifQ.VA_7ZrkzNaCc4LnhXJvamg-LWcuOphmzCOR-Mi8bRg4

###
PUT http://127.0.0.1:8000/orders/d75f6760-e075-4f4c-ab4f-b8c1d41ae5ad/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzkzNjQ4LCJpYXQiOjE3NjA3OTMzNDgsImp0aSI6ImQwNWU2MWE1NmU1NTRiOWRiYmEzYWE3OTlhN2Y1N2JlIiwidXNlcl9pZCI6IjIifQ.eCosJxdCKuTPQhBR7krGF5C3WOEg3QZHzdY_23ouAe0

{
  "status": "confirmed",
  "items": [
    {
      "product": 2,
      "quantity": 5
    },
    {
      "product": 3,
      "quantity": 15
    }
  ]
}

###
DELETE  http://127.0.0.1:8000/orders/d75f6760-e075-4f4c-ab4f-b8c1d41ae5ad/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNzk0MTA2LCJpYXQiOjE3NjA3OTM4MDYsImp0aSI6IjI5YWU0YzY1ZDA1ODRkNzdhODk1ZGY2Y2M5MzI2MGRiIiwidXNlcl9pZCI6IjIifQ.VA_7ZrkzNaCc4LnhXJvamg-LWcuOphmzCOR-Mi8bRg4
