# Generated by Django 5.1.1 on 2025-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptio',
            new_name='description',
        ),
    ]
